CREATE TABLE admins (
    id INT AUTO_INCREMENT PRIMARY KEY,

    name VARCHAR(50) NOT NULL,

    password VARCHAR(255) NOT NULL,

    email VARCHAR(150) NOT NULL UNIQUE,

    role VARCHAR(50) NOT NULL,

    is_approved BOOLEAN DEFAULT FALSE,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);