
CREATE TABLE limits (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tier_order INT NOT NULL UNIQUE,
    limit_count INT NOT NULL,
    price DECIMAL(12,2) NOT NULL,
    days INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
);
