USE ceylone_property;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    full_name VARCHAR(150) NULL,
    google_id VARCHAR(100) NULL UNIQUE,
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NULL,
    auth_type ENUM('email', 'google') NOT NULL DEFAULT 'email',
    picture VARCHAR(500) NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    rate INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);